comment:
  behavior: once
  require_changes: true
  after_n_builds: 2

coverage:
  status:
    project: false
    patch: true

# TODO: add coverage for the python compiler interface
ignore:
  - "frontend/catalyst/python_interface"
