#include "iostream"
#include <algorithm>
#include <algorithm> // generate_n
#include <algorithm>
#include <algorithm> // std::find
#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cassert> // assert
#include <chrono>
#include <cmath>
#include <cmath> // std::ceil()
#include <cmath>
#include <complex.h>
#include <complex>
#include <concepts>
#include <csignal>
#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <exception>
#include <filesystem>
#include <filesystem> // path
#include <filesystem>
#include <fstream>
#include <fstream> // ifstream
#include <fstream>
#include <functional>
#include <functional> // std::reference_wrapper
#include <iomanip>
#include <ios>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <numeric>
#include <optional>
#include <ostream>
#include <queue>
#include <random>
#include <ratio>
#include <regex>
#include <regex> //regex
#include <set>
#include <sstream>
#include <stdbool.h>
#include <stddef.h>
#include <stdexcept>
#include <stdint.h>
#include <stdio.h>
#include <string>
#include <string_view>
#include <sys/time.h>
#include <tuple>
#include <type_traits>
#include <typeinfo>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <utility> // std::forward
#include <utility> // std::move
#include <utility>
#include <variant>
#include <vector>

#include "Enzyme.h"
#include "absl/base/dynamic_annotations.h"
#include "gmock/gmock.h"
#include "gmock/gmock.h" // HasSubstr
#include "gtest/gtest.h"
#include "hlo-extensions/Transforms/Passes.h"
#include "hlo-extensions/Transforms/Patterns.h"
#include "jax_cpu_lapack_kernels/lapack_kernels.hpp"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseMapInfo.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/STLForwardCompat.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringRef.h" // llvm::StringRef
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/ADT/TypeSwitch.h" // needed for generated type parser
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/ADT/TypeSwitch.h" // needed for generated type parser
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/ADT/TypeSwitch.h" // needed for generated type parser
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/ADT/TypeSwitch.h" // needed for generated type parser
#include "llvm/ADT/TypeSwitch.h" // needed for enums
#include "llvm/ADT/TypeSwitch.h" // needed for generated type parser
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/ADT/TypeSwitch.h" // needed for generated type parser
#include "llvm/Analysis/CGSCCPassManager.h"
#include "llvm/Analysis/LoopAnalysisManager.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LLVMContext.h" // llvm::LLVMContext
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Module.h" // llvm::Module
#include "llvm/IR/Module.h"
#include "llvm/IRReader/IRReader.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Support/AllocatorBase.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/LogicalResult.h"
#include "llvm/Support/LogicalResult.h" // llvm::LogicalResult
#include "llvm/Support/LogicalResult.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/MathExtras.h" // for llvm::numbers::pi
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/MemoryBuffer.h" // llvm::MemoryBuffer
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SMLoc.h" // llvm::SMLoc
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/SourceMgr.h" // llvm::SMDiagnostic
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/SourceMgr.h" // llvm::SourceMgr
#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/TargetParser/Host.h"
#include "llvm/Transforms/Coroutines/CoroCleanup.h"
#include "llvm/Transforms/Coroutines/CoroConditionalWrapper.h"
#include "llvm/Transforms/Coroutines/CoroEarly.h"
#include "llvm/Transforms/Coroutines/CoroSplit.h"
#include "llvm/Transforms/IPO/GlobalDCE.h"
#include "mlir-c/Dialect/Arith.h"
#include "mlir-c/IR.h"
#include "mlir/Analysis/CallGraph.h"
#include "mlir/Analysis/Liveness.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Analysis/TopologicalSortUtils.h"
#include "mlir/AsmParser/AsmParser.h"
#include "mlir/AsmParser/AsmParserState.h"
#include "mlir/Bindings/Python/Nanobind.h"
#include "mlir/Bindings/Python/NanobindAdaptors.h"
#include "mlir/Bindings/Python/PybindAdaptors.h"
#include "mlir/Bytecode/BytecodeOpInterface.h"
#include "mlir/Bytecode/BytecodeWriter.h"
#include "mlir/Bytecode/BytecodeWriter.h" // mlir::writeBytecodeToFile
#include "mlir/CAPI/Registration.h"
#include "mlir/Conversion/AffineToStandard/AffineToStandard.h"
#include "mlir/Conversion/ArithToLLVM/ArithToLLVM.h"
#include "mlir/Conversion/BufferizationToMemRef/BufferizationToMemRef.h"
#include "mlir/Conversion/ComplexToLLVM/ComplexToLLVM.h"
#include "mlir/Conversion/ComplexToStandard/ComplexToStandard.h"
#include "mlir/Conversion/ControlFlowToLLVM/ControlFlowToLLVM.h"
#include "mlir/Conversion/FuncToLLVM/ConvertFuncToLLVM.h"
#include "mlir/Conversion/IndexToLLVM/IndexToLLVM.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/MemRefBuilder.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Conversion/LLVMCommon/TypeConverter.h"
#include "mlir/Conversion/MathToLLVM/MathToLLVM.h"
#include "mlir/Conversion/MathToLibm/MathToLibm.h"
#include "mlir/Conversion/MemRefToLLVM/MemRefToLLVM.h"
#include "mlir/Conversion/ReconcileUnrealizedCasts/ReconcileUnrealizedCasts.h"
#include "mlir/Conversion/SCFToControlFlow/SCFToControlFlow.h"
#include "mlir/Conversion/TensorToLinalg/TensorToLinalgPass.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/IR/Arith.h" // for arith::XOrIOp and arith::ConstantOp
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Transforms/Passes.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/Async/IR/Async.h"
#include "mlir/Dialect/Bufferization/IR/AllocationOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/IR/UnstructuredControlFlow.h"
#include "mlir/Dialect/Bufferization/Transforms/BufferUtils.h"
#include "mlir/Dialect/Bufferization/Transforms/Bufferize.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/Complex/IR/Complex.h"
#include "mlir/Dialect/Func/Extensions/AllExtensions.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Index/IR/IndexDialect.h"
#include "mlir/Dialect/Index/IR/IndexOps.h"
#include "mlir/Dialect/LLVMIR/FunctionCallUtils.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/Transforms/Passes.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SCF/Transforms/Patterns.h"
#include "mlir/Dialect/SCF/Utils/Utils.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h" // TF:llvm-project
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Transform/IR/TransformOps.h"
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
#include "mlir/Dialect/Transform/Transforms/TransformInterpreterUtils.h"
#include "mlir/Dialect/UB/IR/UBOps.h"
#include "mlir/ExecutionEngine/CRunnerUtils.h"
#include "mlir/ExecutionEngine/RunnerUtils.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Block.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinOps.h" // mlir::ModuleOp
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinOps.h" // mlir::ModuleOp
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypeInterfaces.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Diagnostics.h" // mlir::Diagnostic
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/DialectImplementation.h" // needed for generated type parser
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/DialectImplementation.h" // needed for generated type parser
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/DialectImplementation.h" // needed for generated type parser
#include "mlir/IR/DialectRegistry.h"
#include "mlir/IR/DialectRegistry.h" // mlir::DialectRegistry
#include "mlir/IR/DialectRegistry.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/MLIRContext.h" // mlir::MLIRContext
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/OwningOpRef.h"
#include "mlir/IR/OwningOpRef.h" // mlir::OwningOpRef
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Region.h"
#include "mlir/IR/RegionKindInterface.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/IR/TypeRange.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/IR/Types.h"
#include "mlir/IR/Value.h"
#include "mlir/IR/ValueRange.h"
#include "mlir/IR/Verifier.h"
#include "mlir/InitAllDialects.h"
#include "mlir/InitAllExtensions.h"
#include "mlir/InitAllPasses.h"
#include "mlir/InitAllTranslations.h"
#include "mlir/Interfaces/CallInterfaces.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/Interfaces/FunctionImplementation.h"
#include "mlir/Interfaces/FunctionInterfaces.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Interfaces/LoopLikeInterface.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/AnalysisManager.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassInstrumentation.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Pass/PassManager.h" // mlir::PassManager
#include "mlir/Pass/PassManager.h"
#include "mlir/Pass/PassManager.h" // for PassManager
#include "mlir/Pass/PassManager.h"
#include "mlir/Rewrite/FrozenRewritePatternSet.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Support/LogicalResult.h" // llvm::LogicalResult
#include "mlir/Support/LogicalResult.h"
#include "mlir/Support/Timing.h"
#include "mlir/Support/Timing.h" // mlir::DefaultTimingManager, mlir::TimingScope
#include "mlir/Support/WalkResult.h"
#include "mlir/Target/LLVMIR/Dialect/Builtin/BuiltinToLLVMIRTranslation.h"
#include "mlir/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.h"
#include "mlir/Target/LLVMIR/Export.h"
#include "mlir/Target/LLVMIR/LLVMTranslationInterface.h"
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
#include "mlir/Tools/Plugins/DialectPlugin.h"
#include "mlir/Tools/Plugins/PassPlugin.h"
#include "mlir/Tools/mlir-lsp-server/MlirLspServerMain.h"
#include "mlir/Tools/mlir-opt/MlirOptMain.h"
#include "mlir/Tools/mlir-translate/MlirTranslateMain.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "mlir/Transforms/CSE.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/InliningUtils.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/Passes.h" // for createCSEPass
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/WalkPatternRewriteDriver.h"
#include "numpy/ndarrayobject.h"
#include "stablehlo/conversions/linalg/transforms/Passes.h"
#include "stablehlo/dialect/Register.h"
#include "stablehlo/dialect/StablehloOps.h"
#include "stablehlo/integrations/c/StablehloPasses.h"
#include "stablehlo/transforms/Passes.h"
#include "stablehlo/transforms/optimization/Passes.h"
#include "xla/service/custom_call_status.h"
#include <boost/multiprecision/cpp_dec_float.hpp>
#include <boost/multiprecision/cpp_int.hpp>
#include <boost/multiprecision/miller_rabin.hpp>
#include <boost/random.hpp>
#include <catch2/catch_approx.hpp>
#include <catch2/catch_session.hpp>
#include <catch2/catch_template_test_macros.hpp>
#include <catch2/catch_test_macros.hpp>
#include <catch2/generators/catch_generators_all.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
#include <catch2/matchers/catch_matchers_range_equals.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>
#include <catch2/matchers/catch_matchers_vector.hpp>
#include <dlfcn.h>
#include <llvm/Target/TargetMachine.h>
#include <mlir/Dialect/Arith/IR/Arith.h>
#include <mlir/Dialect/Arith/IR/Arith.h> // for arith::XOrIOp and arith::ConstantOp
#include <mlir/Dialect/Arith/IR/Arith.h>
#include <mlir/Dialect/SCF/IR/SCF.h>
#include <mlir/Dialect/SCF/Transforms/Transforms.h>
#include <mlir/IR/Builders.h>
#include <mlir/IR/DialectRegistry.h>
#include <mlir/IR/Location.h>
#include <mlir/IR/PatternMatch.h>
#include <mlir/IR/Value.h>
#include <mlir/Support/LogicalResult.h>
#include <nanobind/eval.h>
#include <nanobind/nanobind.h>
#include <nanobind/stl/string.h>
#include <nlohmann/json.hpp>
#include <pybind11/embed.h>
#include <pybind11/eval.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <stim/mem/simd_word.h>
#include <stim/stabilizers/flex_pauli_string.h>
#include <stim/stabilizers/pauli_string.h>
#include <toml++/toml.hpp>

#include "CAPI/Dialects.h"
#include "Catalyst/Analysis/ResourceAnalysis.h"
#include "Catalyst/Analysis/ResourceResult.h"
#include "Catalyst/IR/CatalystDialect.h"
#include "Catalyst/IR/CatalystOps.h"
#include "Catalyst/Transforms/AsyncUtils.h"
#include "Catalyst/Transforms/BufferizableOpInterfaceImpl.h"
#include "Catalyst/Transforms/Passes.h"
#include "Catalyst/Transforms/Patterns.h"
#include "Catalyst/Transforms/TBAAUtils.h"
#include "Catalyst/Utils/CallGraph.h"
#include "Catalyst/Utils/EnsureFunctionDeclaration.h"
#include "Catalyst/Utils/JSONUtils.h"
#include "Catalyst/Utils/PrintVersion.h"
#include "Catalyst/Utils/SCFUtils.h"
#include "Catalyst/Utils/StaticAllocas.h"
#include "Catalyst/Utils/frontend_catalyst_version_py.h"
#include "Catalyst/Utils/frontend_catalyst_version_py.h" // CATALYST_VERSION
#include "Driver/CatalystLLVMTarget.h"
#include "Driver/CompilerDriver.h"
#include "Driver/HighResolutionOutputStrategy.h"
#include "Driver/LineUtils.h"
#include "Driver/PassInstrumentation.h"
#include "Driver/Pipelines.h"
#include "Driver/Support.h"
#include "Driver/Timer.h"
#include "GradMethods/Adjoint.hpp"
#include "GradMethods/FiniteDifference.hpp"
#include "GradMethods/HybridGradient.hpp"
#include "GradMethods/JVPVJPPatterns.hpp"
#include "GradMethods/ParameterShift.hpp"
#include "Gradient/IR/GradientDialect.h"
#include "Gradient/IR/GradientInterfaces.h"
#include "Gradient/IR/GradientOps.h"
#include "Gradient/Transforms/BufferizableOpInterfaceImpl.h"
#include "Gradient/Transforms/EnzymeConstants.h"
#include "Gradient/Transforms/Passes.h"
#include "Gradient/Transforms/Patterns.h"
#include "Gradient/Transforms/Utils.h"
#include "Gradient/Transforms/annotate_invalid_gradient_functions.h"
#include "Gradient/Utils/DestinationPassingStyle.h"
#include "Gradient/Utils/DifferentialQNode.h"
#include "Gradient/Utils/EinsumLinalgGeneric.h"
#include "Gradient/Utils/GradientShape.h"
#include "Ion/IR/IonDialect.h"
#include "Ion/IR/IonInfo.h"
#include "Ion/IR/IonInterfaces.h"
#include "Ion/IR/IonOps.h"
#include "Ion/Transforms/Passes.h"
#include "Ion/Transforms/Patterns.h"
#include "Ion/Transforms/ValueTracing.h"
#include "Ion/Transforms/oqd_database_managers.hpp"
#include "Ion/Transforms/oqd_database_types.hpp"
#include "MBQC/IR/MBQCDialect.h"
#include "MBQC/IR/MBQCInterfaces.h"
#include "MBQC/IR/MBQCOps.h"
#include "MBQC/Transforms/Passes.h"
#include "MBQC/Transforms/Patterns.h"
#include "Mitigation/IR/MitigationDialect.h"
#include "Mitigation/IR/MitigationOps.h"
#include "Mitigation/Transforms/Passes.h"
#include "Mitigation/Transforms/Patterns.h"
#include "MitigationMethods/Zne.hpp"
#include "PBC/IR/PBCDialect.h"
#include "PBC/IR/PBCOpInterfaces.h"
#include "PBC/IR/PBCOps.h"
#include "PBC/IR/PBCOps.h" // for FabricateOp
#include "PBC/IR/PBCOps.h"
#include "PBC/Transforms/PPRDecomposeUtils.h"
#include "PBC/Transforms/Passes.h"
#include "PBC/Transforms/Patterns.h"
#include "PBC/Utils/PBCLayer.h"
#include "PBC/Utils/PBCOpUtils.h"
#include "PBC/Utils/PauliStringWrapper.h"
#include "PauliFrame/IR/PauliFrameDialect.h"
#include "PauliFrame/IR/PauliFrameOps.h"
#include "PauliFrame/Transforms/Passes.h"
#include "PauliFrame/Transforms/Patterns.h"
#include "QRef/IR/QRefDialect.h"
#include "QRef/IR/QRefInterfaces.h"
#include "QRef/IR/QRefOps.h"
#include "QRef/IR/QRefTypes.h"
#include "QRef/Transforms/Passes.h"
#include "QRef/Transforms/value_semantics_conversion.h"
#include "QecLogical/IR/QecLogicalAttrDefs.h"
#include "QecLogical/IR/QecLogicalDialect.h"
#include "QecLogical/IR/QecLogicalOps.h"
#include "QecLogical/IR/QecLogicalTypes.h"
#include "QecPhysical/IR/QecPhysicalAttrDefs.h"
#include "QecPhysical/IR/QecPhysicalDialect.h"
#include "QecPhysical/IR/QecPhysicalOps.h"
#include "QecPhysical/IR/QecPhysicalTypes.h"
#include "Quantum/IR/QuantumAttrDefs.h"
#include "Quantum/IR/QuantumDialect.h"
#include "Quantum/IR/QuantumInterfaces.h"
#include "Quantum/IR/QuantumOps.h"
#include "Quantum/IR/QuantumOps.h" // for quantum.extract op
#include "Quantum/IR/QuantumOps.h"
#include "Quantum/IR/QuantumOps.h" // for quantum::AllocQubitOp
#include "Quantum/IR/QuantumOps.h"
#include "Quantum/IR/QuantumTypes.h"
#include "Quantum/Transforms/BufferizableOpInterfaceImpl.h"
#include "Quantum/Transforms/Passes.h"
#include "Quantum/Transforms/Patterns.h"
#include "Quantum/Utils/QuantumSplitting.h"
#include "Quantum/Utils/RemoveQuantum.h"
#include "RTIO/IR/RTIODialect.h"
#include "RTIO/IR/RTIOOps.h"
#include "RTIO/IR/RTIOOps.h" // For ConfigAttr
#include "RTIO/IR/RTIOOps.h"
#include "RTIO/Transforms/Passes.h"
#include "RTIO/Transforms/Patterns.h"
#include "Standalone-c/Dialects.h"
#include "Standalone/StandaloneDialect.h"
#include "Standalone/StandaloneOps.h"
#include "Standalone/StandalonePasses.h"
#include "Standalone/StandaloneTypes.h"
#include "Test/Transforms/Passes.h"

#include "ARTIQRuntimeBuilder.hpp"
#include "Adjoint.hpp"
#include "ClassicalJacobian.hpp"
#include "CliffordData.hpp"
#include "CompilerDriver.h"
#include "DataView.hpp"
#include "DecomposeLoweringImpl.hpp"
#include "DynamicLibraryLoader.hpp"
#include "Ellipse.hpp"
#include "Exception.hpp"
#include "ExecutionContext.hpp"
#include "FiniteDifference.hpp"
#include "GridProblems.hpp"
#include "HybridGradient.hpp"
#include "JVPVJPPatterns.hpp"
#include "MemRefUtils.hpp"
#include "NormSolver.hpp"
#include "NormalForms.hpp"
#include "NullQubit.hpp"
#include "OQCDevice.cpp"
#include "OQCDevice.hpp"
#include "OQCRunner.hpp"
#include "OQDDevice.hpp"
#include "OQDRuntimeCAPI.h"
#include "OpenQASM2Builder.hpp"
#include "OpenQasmBuilder.hpp"
#include "OpenQasmDevice.hpp"
#include "OpenQasmObsManager.hpp"
#include "OpenQasmRunner.hpp"
#include "ParameterShift.hpp"
#include "PropagateSimpleStatesAnalysis.hpp"
#include "QuantumDevice.hpp"
#include "QubitManager.hpp"
#include "RSDecomp.hpp"
#include "RSUtils.hpp"
#include "RegisterAllPasses.h"
#include "ResourceTracker.hpp"
#include "Rings.cpp"
#include "Rings.hpp"
#include "RuntimeCAPI.h"
#include "TestUtils.hpp"
#include "Timer.h"
#include "Types.h"
#include "Utils.hpp"
#include "VerifyParentGateAnalysis.hpp"
#include "Zne.hpp"
#include "lapack_kernels.hpp"
#include "oqd_database_types.hpp"
#include "oqd_database_utils.hpp"
#include <Exception.hpp>
#include <NullQubit.hpp>
#include <QuantumDevice.hpp>

#include "Catalyst/IR/CatalystOps.cpp.inc"
#include "Catalyst/IR/CatalystOps.h.inc"
#include "Catalyst/IR/CatalystOpsDialect.cpp.inc"
#include "Catalyst/IR/CatalystOpsDialect.h.inc"
#include "Catalyst/IR/CatalystOpsTypes.cpp.inc"
#include "Catalyst/IR/CatalystOpsTypes.h.inc"
#include "Catalyst/Transforms/Passes.h.inc"
#include "Gradient/IR/GradientInterfaces.cpp.inc"
#include "Gradient/IR/GradientInterfaces.h.inc"
#include "Gradient/IR/GradientOps.cpp.inc"
#include "Gradient/IR/GradientOps.h.inc"
#include "Gradient/IR/GradientOpsDialect.cpp.inc"
#include "Gradient/IR/GradientOpsDialect.h.inc"
#include "Gradient/Transforms/Passes.h.inc"
#include "Ion/IR/IonAttributes.cpp.inc"
#include "Ion/IR/IonAttributes.h.inc"
#include "Ion/IR/IonEnums.cpp.inc"
#include "Ion/IR/IonInterfaces.cpp.inc"
#include "Ion/IR/IonInterfaces.h.inc"
#include "Ion/IR/IonOps.cpp.inc"
#include "Ion/IR/IonOps.h.inc"
#include "Ion/IR/IonOpsDialect.cpp.inc"
#include "Ion/IR/IonOpsDialect.h.inc"
#include "Ion/IR/IonOpsTypes.cpp.inc"
#include "Ion/IR/IonOpsTypes.h.inc"
#include "Ion/Transforms/Passes.h.inc"
#include "MBQC/IR/MBQCAttributes.cpp.inc"
#include "MBQC/IR/MBQCAttributes.h.inc"
#include "MBQC/IR/MBQCEnums.cpp.inc"
#include "MBQC/IR/MBQCEnums.h.inc"
#include "MBQC/IR/MBQCInterfaces.cpp.inc"
#include "MBQC/IR/MBQCInterfaces.h.inc"
#include "MBQC/IR/MBQCOps.cpp.inc"
#include "MBQC/IR/MBQCOps.h.inc"
#include "MBQC/IR/MBQCOpsDialect.cpp.inc"
#include "MBQC/IR/MBQCOpsDialect.h.inc"
#include "MBQC/Transforms/Passes.h.inc"
#include "Mitigation/IR/MitigationAttributes.cpp.inc"
#include "Mitigation/IR/MitigationAttributes.h.inc"
#include "Mitigation/IR/MitigationEnums.cpp.inc"
#include "Mitigation/IR/MitigationEnums.h.inc"
#include "Mitigation/IR/MitigationOps.cpp.inc"
#include "Mitigation/IR/MitigationOps.h.inc"
#include "Mitigation/IR/MitigationOpsDialect.cpp.inc"
#include "Mitigation/IR/MitigationOpsDialect.h.inc"
#include "Mitigation/IR/MitigationOpsTypes.cpp.inc"
#include "Mitigation/Transforms/Passes.h.inc"
#include "PBC/IR/PBCAttributes.cpp.inc"
#include "PBC/IR/PBCAttributes.h.inc"
#include "PBC/IR/PBCEnums.cpp.inc"
#include "PBC/IR/PBCEnums.h.inc"
#include "PBC/IR/PBCOpInterfaces.cpp.inc"
#include "PBC/IR/PBCOpInterfaces.h.inc"
#include "PBC/IR/PBCOps.cpp.inc"
#include "PBC/IR/PBCOps.h.inc"
#include "PBC/IR/PBCOpsDialect.cpp.inc"
#include "PBC/IR/PBCOpsDialect.h.inc"
#include "PBC/IR/PBCOpsTypes.cpp.inc"
#include "PBC/IR/PBCOpsTypes.h.inc"
#include "PBC/Transforms/Passes.h.inc"
#include "PBC/Transforms/PassesEnums.h.inc"
#include "PBC/Transforms/PassesEnums.h.inc" // need for DecomposeMethod
#include "PBC/Transforms/PassesEnums.h.inc" // for DecomposeMethod
#include "PauliFrame/IR/PauliFrameAttributes.cpp.inc"
#include "PauliFrame/IR/PauliFrameAttributes.h.inc"
#include "PauliFrame/IR/PauliFrameEnums.cpp.inc"
#include "PauliFrame/IR/PauliFrameEnums.h.inc"
#include "PauliFrame/IR/PauliFrameOps.cpp.inc"
#include "PauliFrame/IR/PauliFrameOps.h.inc"
#include "PauliFrame/IR/PauliFrameOpsDialect.cpp.inc"
#include "PauliFrame/IR/PauliFrameOpsDialect.h.inc"
#include "PauliFrame/Transforms/Passes.h.inc"
#include "QRef/IR/QRefInterfaces.cpp.inc"
#include "QRef/IR/QRefInterfaces.h.inc"
#include "QRef/IR/QRefOps.cpp.inc"
#include "QRef/IR/QRefOps.h.inc"
#include "QRef/IR/QRefOpsDialect.cpp.inc"
#include "QRef/IR/QRefOpsDialect.h.inc"
#include "QRef/IR/QRefOpsTypes.cpp.inc"
#include "QRef/IR/QRefOpsTypes.h.inc"
#include "QRef/Transforms/Passes.h.inc"
#include "QecLogical/IR/QecLogicalAttributes.cpp.inc"
#include "QecLogical/IR/QecLogicalAttributes.h.inc"
#include "QecLogical/IR/QecLogicalEnums.cpp.inc"
#include "QecLogical/IR/QecLogicalEnums.h.inc"
#include "QecLogical/IR/QecLogicalOps.cpp.inc"
#include "QecLogical/IR/QecLogicalOps.h.inc"
#include "QecLogical/IR/QecLogicalOpsDialect.cpp.inc"
#include "QecLogical/IR/QecLogicalOpsDialect.h.inc"
#include "QecLogical/IR/QecLogicalOpsTypes.cpp.inc"
#include "QecLogical/IR/QecLogicalOpsTypes.h.inc"
#include "QecPhysical/IR/QecPhysicalAttributes.cpp.inc"
#include "QecPhysical/IR/QecPhysicalAttributes.h.inc"
#include "QecPhysical/IR/QecPhysicalEnums.cpp.inc"
#include "QecPhysical/IR/QecPhysicalEnums.h.inc"
#include "QecPhysical/IR/QecPhysicalOps.cpp.inc"
#include "QecPhysical/IR/QecPhysicalOps.h.inc"
#include "QecPhysical/IR/QecPhysicalOpsDialect.cpp.inc"
#include "QecPhysical/IR/QecPhysicalOpsDialect.h.inc"
#include "QecPhysical/IR/QecPhysicalOpsTypes.cpp.inc"
#include "QecPhysical/IR/QecPhysicalOpsTypes.h.inc"
#include "Quantum/IR/QuantumAttributes.cpp.inc"
#include "Quantum/IR/QuantumAttributes.h.inc"
#include "Quantum/IR/QuantumEnums.cpp.inc"
#include "Quantum/IR/QuantumEnums.h.inc"
#include "Quantum/IR/QuantumInterfaces.cpp.inc"
#include "Quantum/IR/QuantumInterfaces.h.inc"
#include "Quantum/IR/QuantumOps.cpp.inc"
#include "Quantum/IR/QuantumOps.h.inc"
#include "Quantum/IR/QuantumOpsDialect.cpp.inc"
#include "Quantum/IR/QuantumOpsDialect.h.inc"
#include "Quantum/IR/QuantumOpsTypes.cpp.inc"
#include "Quantum/IR/QuantumOpsTypes.h.inc"
#include "Quantum/Transforms/Passes.h.inc"
#include "RTIO/IR/RTIOAttributes.cpp.inc"
#include "RTIO/IR/RTIOAttributes.h.inc"
#include "RTIO/IR/RTIOOps.cpp.inc"
#include "RTIO/IR/RTIOOps.h.inc"
#include "RTIO/IR/RTIOOpsDialect.cpp.inc"
#include "RTIO/IR/RTIOOpsDialect.h.inc"
#include "RTIO/IR/RTIOOpsTypes.cpp.inc"
#include "RTIO/IR/RTIOOpsTypes.h.inc"
#include "RTIO/Transforms/Passes.h.inc"
#include "Standalone/StandaloneOps.cpp.inc"
#include "Standalone/StandaloneOps.h.inc"
#include "Standalone/StandaloneOpsDialect.cpp.inc"
#include "Standalone/StandaloneOpsDialect.h.inc"
#include "Standalone/StandaloneOpsTypes.cpp.inc"
#include "Standalone/StandaloneOpsTypes.h.inc"
#include "Standalone/StandalonePasses.h.inc"
#include "Test/Transforms/Passes.h.inc"
#include "hlo-extensions/Transforms/Passes.h.inc"
#include "hlo-extensions/Transforms/generated_stablehlo_legalize_to_standard.cpp.inc"
