# Read the Docs configuration file

# Required
version: 2

# Build documentation with Sphinx
sphinx:
  configuration: doc/conf.py

# Exclude all submodules
submodules:
  exclude: all

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - htmlzip

# Optionally set the build image
build:
  os: ubuntu-22.04
  tools:
      python: "3.10"
  apt_packages:
    - graphviz
    - cmake
    - ninja-build
    - clang

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
