# Based on Lightning's lightning_qubit.toml. It is better if we keep it updated.
schema = 3

# The set of all gate types supported at the runtime execution interface of the
# device, i.e., what is supported by the `execute` method of the Device API.
# The gate definition has the following format:
#
#   GATE = { properties = [ PROPS ], conditions = [ CONDS ] }
#
# where PROPS and CONS are zero or more comma separated quoted strings.
#
# PROPS: zero or more comma-separated quoted strings:
#        - "controllable": if a controlled version of this gate is supported.
#        - "invertible": if the adjoint of this operation is supported.
#        - "differentiable": if device gradient is supported for this gate.
# CONDS: zero or more comma-separated quoted strings:
#        - "analytic" or "finiteshots": if this operation is only supported in
#          either analytic execution or with shots, respectively.
#        - "terms-commute": if this composite operator is only supported
#          given that its terms commute. Only relevant for Prod, SProd, Sum,
#          LinearCombination, and Hamiltonian.
#
[operators.gates]

CNOT                   = { properties = [ "invertible" ] }
Hadamard               = { properties = [ "invertible" ] }
Identity               = { properties = [ "invertible" ] }
PauliRot               = { properties = [ "invertible" ] }
PauliMeasure           = { properties = [] }
PauliX                 = { properties = [ "invertible" ] }
PauliY                 = { properties = [ "invertible" ] }
PauliZ                 = { properties = [ "invertible" ] }
S                      = { properties = [ "invertible" ] }
T                      = { properties = [ "invertible" ] }

# Observables supported by the device
[operators.observables]

[measurement_processes]

[compilation]

# If the device is compatible with qjit
qjit_compatible = true
# If the device requires run time generation of the quantum circuit.
runtime_code_generation = false
# If the device supports mid-circuit measurements natively
supported_mcm_methods = [ "device", "one-shot" ]
# This field is currently unchecked, but it is reserved for the purpose of
# determining if the device supports dynamic qubit allocation/deallocation.
dynamic_qubit_management = false
# whether the device can support non-commuting measurements together
# in a single execution
non_commuting_observables = true
# Whether the device supports (arbitrary) initial state preparation.
initial_state_prep = true
