// Copyright 2024 Xanadu Quantum Technologies Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This nanobind module is dlopen'd at runtime by PLPythonRunner.
// It bridges the C++ runtime back into the Python interpreter to execute
// PennyLane QuantumScript tapes on arbitrary PennyLane Python devices.
//
// Pattern: identical to openqasm_python_module.cpp (Braket backend), except
// we deserialize JSON tape -> PennyLane QuantumScript -> device.execute().

#include <cmath>
#include <cstring>
#include <complex>
#include <string>
#include <vector>

#include "nanobind/eval.h"
#include "nanobind/nanobind.h"
#include "nanobind/stl/string.h"
#include "nanobind/nanobind.h"

#include <nanobind/make_iterator.h>

// The Python code that reconstructs a PennyLane tape from JSON and executes it.
const std::string program = R"(
import json
import numpy as np
import pennylane as qml
from pennylane.tape import QuantumScript


def _get_op(name, params, wires, inverse, ctrl_wires, ctrl_values):
    """Instantiate a PennyLane operator from its serialized form."""
    op_cls = getattr(qml, name, None)
    if op_cls is None:
        op_cls = getattr(qml.ops, name, None)
    if op_cls is None:
        raise ValueError(f"Unknown PennyLane gate: {name}")

    if params:
        op = op_cls(*params, wires=wires)
    else:
        op = op_cls(wires=wires)

    if inverse:
        op = qml.adjoint(op)

    if ctrl_wires:
        cv = [bool(v) for v in ctrl_values] if ctrl_values else None
        op = qml.ctrl(op, control=ctrl_wires, control_values=cv)

    return op

def _create_tape(ops, meas, shots_val):
    """Safely construct a tape, treating 0 as analytic (None)."""
    tape_shots = int(shots_val) if shots_val and int(shots_val) > 0 else None
    return QuantumScript(ops, meas, shots=tape_shots)

def _build_tape(tape_json):
    """Deserialize JSON into a list of PennyLane operations."""
    data = json.loads(tape_json)
    ops = []

    for g in data["ops"]:
        if g["name"] == "MidCircuitMeasure":
            # Mid-circuit measurement
            ops.append(qml.measure(g["wires"][0]))
        else:
            op = _get_op(g["name"], g["params"], g["wires"],
                         g["inverse"], g["ctrl_wires"], g["ctrl_values"])
            ops.append(op)

    # Matrix operations (QubitUnitary)
    for mg in data.get("matrix_ops", []):
        mat_re = np.array(mg["matrix_re"])
        mat_im = np.array(mg["matrix_im"])
        mat = (mat_re + 1j * mat_im).reshape(
            int(np.sqrt(len(mat_re))), int(np.sqrt(len(mat_re))))
        op = qml.QubitUnitary(mat, wires=mg["wires"])
        if mg["inverse"]:
            op = qml.adjoint(op)
        if mg["ctrl_wires"]:
            cv = [bool(v) for v in mg["ctrl_values"]] if mg["ctrl_values"] else None
            op = qml.ctrl(op, control=mg["ctrl_wires"], control_values=cv)
        ops.append(op)

    return ops, data["num_qubits"]


def _build_obs(obs_json, num_qubits):
    """Deserialize JSON observables array into PennyLane observable objects."""
    obs_list = json.loads(obs_json)
    pl_obs = []

    for obs_data in obs_list:
        kind = obs_data["kind"]
        if kind == "named":
            obs_cls = getattr(qml, obs_data["name"])
            pl_obs.append(obs_cls(wires=obs_data["wires"]))
        elif kind == "hermitian":
            mat_re = np.array(obs_data["matrix_re"])
            mat_im = np.array(obs_data["matrix_im"])
            n = int(np.sqrt(len(mat_re)))
            mat = (mat_re + 1j * mat_im).reshape(n, n)
            pl_obs.append(qml.Hermitian(mat, wires=obs_data["wires"]))
        elif kind == "tensor":
            sub = [pl_obs[i] for i in obs_data["obs_ids"]]
            pl_obs.append(qml.prod(*sub))
        elif kind == "hamiltonian":
            sub = [pl_obs[i] for i in obs_data["obs_ids"]]
            coeffs = obs_data["coeffs"]
            pl_obs.append(qml.Hamiltonian(coeffs, sub))
        else:
            raise ValueError(f"Unknown observable kind: {kind}")

    return pl_obs

_DEVICE_CACHE = {}

def _get_device(device_kwargs_json):
    """Instantiate the target PennyLane device from serialized kwargs."""
    if device_kwargs_json in _DEVICE_CACHE:
        return _DEVICE_CACHE[device_kwargs_json]

    import base64

    # 1. Parse the naive {"key":"value"} JSON generated by C++ serializeKwargs
    raw_dict = json.loads(device_kwargs_json)

    # 2. Extract and decode the true kwargs payload
    b64_str = raw_dict.get("b64_kwargs", "")
    if b64_str:
        json_str = base64.b64decode(b64_str).decode('utf-8')
        kwargs = json.loads(json_str)
    else:
        kwargs = raw_dict  # Fallback for safety

    # 3. Pop the wrapper-specific arguments
    device_name = kwargs.pop("pl_device_name", "default.qubit")
    wires_str = kwargs.pop("wires", None)
    shots_str = kwargs.pop("shots", None)

    wires = int(wires_str) if wires_str else None
    shots = int(shots_str) if shots_str and shots_str != "0" else None

    # 4. Instantiate the device, unpacking any remaining arbitrary kwargs!
    dev = qml.device(device_name, wires=wires, shots=shots, **kwargs)

    _DEVICE_CACHE[device_kwargs_json] = dev
    return dev

def py_execute(tape_json, obs_json, meas_json, device_kwargs, shots):
    ops, nq = _build_tape(tape_json)
    pl_obs = _build_obs(obs_json, nq)

    # 1. Parse the requested measurement
    m = json.loads(meas_json)
    m_type = m["type"]
    wires = m.get("wires", None)

    # 2. Construct the PennyLane measurement process natively
    if m_type == "probs":
        meas = [qml.probs(wires=wires if wires is not None else range(nq))]
    elif m_type == "sample":
        meas = [qml.sample(wires=wires if wires is not None else range(nq))]
    elif m_type == "expval":
        meas = [qml.expval(pl_obs[m["obs_idx"]])]
    elif m_type == "var":
        meas = [qml.var(pl_obs[m["obs_idx"]])]
    elif m_type == "state":
        meas = [qml.state()]
    else:
        raise ValueError(f"Unknown measurement type: {m_type}")

    # 3. Create the complete tape and execute
    tape = _create_tape(ops, meas, shots)
    dev = _get_device(device_kwargs)
    result = dev.execute(tape)

    # 4. Flatten all results to a standard list of floats for C++
    if m_type == "state":
        sv = np.asarray(result).flatten()
        out = []
        for c in sv:
            out.append(float(c.real))
            out.append(float(c.imag))
        return out
    else:
        return np.asarray(result).flatten().tolist()
)";

// ============================================================================
// Python Scope Management
// ============================================================================

static nanobind::dict& get_python_scope() {
    static nanobind::dict python_scope;
    static bool is_initialized = false;

    if (!is_initialized) {
        // Provide builtins to the isolated scope
        python_scope["__builtins__"] = nanobind::module_::import_("builtins").attr("__dict__");
        // Execute the script once
        nanobind::exec(nanobind::str(program.c_str()), python_scope);
        is_initialized = true;
    }
    return python_scope;
}

// ============================================================================
// extern "C" functions called by PLPythonRunner via dlopen + getSymbol
// ============================================================================

extern "C" NB_EXPORT void pl_execute(const char *_tape, const char *_obs, const char *_meas,
                                     const char *_kwargs, size_t shots, void *_vector)
{
    namespace nb = nanobind;
    nb::gil_scoped_acquire lock;
    nb::dict& scope = get_python_scope(); // Using the cached scope we built earlier

    auto results = scope["py_execute"](std::string(_tape), std::string(_obs),
                                       std::string(_meas), std::string(_kwargs), shots);

    auto *res_vec = reinterpret_cast<std::vector<double> *>(_vector);
    for (nb::handle item : results) {
        res_vec->push_back(nb::cast<double>(item));
    }
}

NB_MODULE(pennylane_python_module, m) { m.doc() = "PennyLane Python device compatibility layer"; }
