@startuml
!include <C4/C4_Container.puml>

!include common.iuml

HIDE_STEREOTYPE()

Boundary(c1, "Catalyst", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {

  Container(_tracer_, "Frontend", "PennyLane and JAX", "Python code tracer and compiler")
  Container(_qopt_, "Core", "LLVM/MLIR", "Quantum-specific dialects, passes and tools")

  Container(_catalyst_runtime_, "Runtime", "C++", "The QIR Runtime backed by qir-stdlib")
}

Boundary(c2, "Backend", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {

  Container_Ext(_pl_lightning_kokkos_, "PennyLane-Lightning-Kokkos", "CPU/GPU")

  Container_Ext(_pl_lightning_, "PennyLane-Lightning", "CPU")

}

Rel_R(_tracer_, _qopt_, "compiles with", "", $tags="action")

Rel_R(_qopt_, _catalyst_runtime_, "links", "", $tags="action")

Rel(_catalyst_runtime_, _pl_lightning_kokkos_, " ", "", $tags="action")

Rel(_catalyst_runtime_, _pl_lightning_, " ", "", $tags="action")

@enduml
