@startuml
!include <C4/C4_Container.puml>

!include common.iuml

HIDE_STEREOTYPE()

Person(_user_, "Programmer", "Writes and runs a compiled quantum program")

Boundary(c1, "Catalyst", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {

  Container(_tracer_, "Frontend", "Python, JAX, MLIR", "Python code tracer and compiler")
  Container(_qopt_, "Quantum-Opt", "MLIR", "Quantum-specific dialects and passes")

  Container(_catalyst_runtime_, "Catalyst-Runtime", "C++", "The QIR Runtime")
}

Boundary(c2, "Simulators", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {

  Container_Ext(_pl_lightning_kokkos_, "PennyLane-Lightning-Kokkos", "CPU/GPU")

  Container_Ext(_pl_lightning_, "PennyLane-Lightning", "CPU")

}

Rel(_user_, _tracer_, "uses", "", $tags="action")

Rel_R(_tracer_, _qopt_, "compiles with", "", $tags="action")

Rel_R(_qopt_, _catalyst_runtime_, "links", "", $tags="action")

Rel(_catalyst_runtime_, _pl_lightning_kokkos_, "calls", "", $tags="action")

Rel(_catalyst_runtime_, _pl_lightning_, "calls", "", $tags="action")

@enduml
