[package]
name = "qir-stdlib"
version = "0.3.0"
authors = ["Microsoft"]
edition = "2021"
license = "MIT"

[dependencies.qir-stdlib]
git = "https://github.com/qir-alliance/qir-runner.git"
tag = "v0.3.0"

[lib]
crate-type = ["staticlib"]
