name: Build Pennylane Lightning Catalyst Docker Image

permissions:
  contents: read
  
on:
    pull_request:
        
jobs:
  check_if_wheel_build_required:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/check-for-wheel-build.yml

  constants:
    needs: [check_if_wheel_build_required]
    name: "Set build matrix"
    uses: ./.github/workflows/constants.yaml
    with:
      runs_on: ubuntu-24.04
  
  check_caches:
    needs: [check_if_wheel_build_required, constants]
    name: Check for cached builds
    runs-on: ubuntu-24.04
    outputs:
      llvm_cached: ${{ steps.llvm.outputs.cache-hit == 'true' }}
      stablehlo_cached: ${{ steps.stablehlo.outputs.cache-hit == 'true' }}
    steps:
      - uses: actions/cache/restore@v6
        id: llvm
        with:
          path: llvm-build
          key: manylinux_2_28_x86_64-llvm-${{ needs.constants.outputs.llvm_version }}-${{ needs.constants.outputs.primary_python_version }}-wheel-build
          lookup-only: true 
      - uses: actions/cache/restore@v6
        id: stablehlo
        with:
          path: stablehlo-build
          key: manylinux_2_28_x86_64-stablehlo-${{ needs.constants.outputs.stablehlo_version }}-wheel-build
          lookup-only: true
    
  build:
    name: Build Docker Image
    runs-on: blacksmith-8vcpu-ubuntu-2404	
    needs: [check_if_wheel_build_required, constants, check_caches]    
    strategy:
      fail-fast: false
      matrix:
        python_version: ${{ fromJson(format('["{0}"]', needs.constants.outputs.primary_python_version)) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Get Cached LLVM Source
        id: cache-llvm-source
        uses: actions/cache/restore@v6
        with:
          path: ${{ github.workspace }}/mlir/llvm-project
          key: llvm-${{ needs.constants.outputs.llvm_version }}-container-source
          enableCrossOsArchive: True
          fail-on-cache-miss: True        

      - name: Get Cached LLVM Build
        id: cache-llvm-build
        uses: actions/cache/restore@v6
        with:
          path: ${{ github.workspace }}/llvm-build
          key: manylinux_2_28_x86_64-llvm-${{ needs.constants.outputs.llvm_version }}-${{ matrix.python_version }}-wheel-build
          fail-on-cache-miss: True
    
      - name: Get Cached Stablehlo Source
        id: cache-stablehlo-source
        uses: actions/cache/restore@v6
        with:
          path: ${{ github.workspace }}/mlir/stablehlo
          key: stablehlo-${{ needs.constants.outputs.stablehlo_version }}-container-source
          enableCrossOsArchive: True
          fail-on-cache-miss: True
  
      - name: Get Cached Stablehlo Build
        id: cache-stablehlo-build
        uses: actions/cache/restore@v6
        with:
          path: ${{ github.workspace }}/stablehlo-build
          key: manylinux_2_28_x86_64-stablehlo-${{ needs.constants.outputs.stablehlo_version }}-wheel-build
          fail-on-cache-miss: True

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          build-args: |
            PENNYLANE_VERSION=main
            CATALYST_VERSION=main
            GITHUB_WORKSPACE=${{ github.workspace }}
            LLVM_CACHE=true
            STABLEHLO_CACHE=false
