name: Build Catalyst Docker Image

permissions:
  contents: read
  
on:
    pull_request:
      types:
        - labeled
    push:
    workflow_dispatch:
      inputs:
        lightning-version:
          type: string
          required: true
          description: The version of Lightning to use. This should be a valid git tag, e.g. v0.36.0.
        pennylane-version:
          type: string
          required: false
          default: main
          description: The version of PennyLane to use. This should be a valid git tag, e.g. v0.36.0.
        
jobs:
  check_if_wheel_build_required:
    uses: ./.github/workflows/check-for-wheel-build.yml

  constants:
    needs: [check_if_wheel_build_required]
    name: "Set build matrix"
    uses: ./.github/workflows/constants.yaml
    with:
      runs_on: ubuntu-24.04

  build-catalyst:
    name: Build Docker Image
    runs-on: blacksmith-8vcpu-ubuntu-2404
    needs: [check_if_wheel_build_required, constants]    
    strategy:
      fail-fast: false
      matrix:
        python_version: ${{ fromJson(format('["{0}"]', needs.constants.outputs.primary_python_version)) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker        

      - name: Checkout External Base Repo
        uses: actions/checkout@v4
        with:
          repository: PennyLaneAI/pennylane-lightning
          ref: main 
          path: pennylane-lightning

      - name: Build Lightning docker image
        uses: docker/build-push-action@v6
        with:
          context: ./pennylane-lightning
          file: ./pennylane-lightning/docker/Dockerfile
          tags: pennylane-lightning:latest
          load: true
          push: false
          build-args: |
            LIGHTNING_VERSION=${{ inputs.lightning-version || 'main' }}
            PENNYLANE_VERSION=${{ inputs.pennylane-version || 'main' }}

      - name: Check docker image
        run: |
          docker images

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: pennylane-catalyst:latest
          load: true
          build-contexts: |
            pennylane-lightning=docker-image://pennylane-lightning:latest
          build-args: |
            LIGHTNING_VERSION=${{ inputs.lightning-version || 'main' }}
            PENNYLANE_VERSION=${{ inputs.pennylane-version || 'main' }}            

      # Serialize the Docker image into a single transportable archive file
      - name: Save Docker Image to Archive
        run: |
          mkdir -p output
          docker save pennylane-catalyst:latest -o output/pennylane-catalyst.tar

      # Upload the archive file so you can download it from the GitHub UI
      - name: Upload Image as Workflow Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-docker-image
          path: output/pennylane-catalyst.tar
          retention-days: 5            