name: Build nightly Catalyst releases for TestPyPI

on:
  schedule:
    # Run every weekday at 23:40 EDT (cron is in UTC)
    - cron: "40 3 * * 2-6"
  workflow_dispatch:
    inputs:
      build-linux-arm:
        description: 'Publish ARM wheels for Linux'
        default: false
        required: false
        type: boolean

jobs:
  setup:
    name: Setup the release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Catalyst repo
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.NIGHTLY_VERSION_UPDATE_DEPLOY_KEY }}

    - name: Bump dev version
      run: |
        python $GITHUB_WORKSPACE/.github/workflows/set_nightly_version.py

    - name: Push new version
      run: |
        git config --global user.email '${{ secrets.AUTO_UPDATE_VERSION_RINGO_EMAIL }}'
        git config --global user.name "ringo-but-quantum"
        git add $GITHUB_WORKSPACE/frontend/catalyst/_version.py
        git commit -m "[no ci] bump nightly version"
        git push

  # Only build the most popular configurations on a nightly schedule to save PyPI storage.

  linux-x86:
    name: Build on Linux x86-64
    needs: [setup]
    uses: ./.github/workflows/build-wheel-linux-x86_64.yaml

  linux-aarch:
    if: ${{ inputs.build-linux-arm }}
    name: Build on Linux aarch64
    needs: [setup]
    uses: ./.github/workflows/build-wheel-linux-arm64.yaml

  macos-arm:
    name: Build on macOS arm64
    needs: [setup]
    uses: ./.github/workflows/build-wheel-macos-arm64.yaml

  upload:
    name: Prepare & Upload wheels to TestPyPI
    if: ${{ !failure() && !cancelled() }}  # needed in case linux-aarch is skipped
    needs: [linux-x86, macos-arm, linux-aarch]
    runs-on: ubuntu-24.04
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
        path: dist

    - name: Install rename
      run: |
        sudo apt install rename

    - name: Prepare wheels
      run: |
        rename "s/linux/manylinux_2_28/" dist/pennylane_catalyst-*
        rename "s/macosx_14_0_universal2/macosx_13_0_arm64/" dist/pennylane_catalyst-*
        rename "s/macosx_14/macosx_13/" dist/pennylane_catalyst-*

    - name: Upload wheels
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        packages-dir: dist
        verbose: true
