name: Check CPL stable/latest/stable

on:
  schedule:
    - chron: "20 10 * * 1-5"
  workflow_dispatch:

jobs:
  build-config:
    name: CPL stable/latest/stable
    uses: ./.github/workflows/check-pl-compat.yaml
    with:
      catalyst: stable
      pennylane: latest
      lightning: stable
