name: Check CPL stable/stable/latest

on:
  schedule:
    - chron: "20 10 * * 1-5"
  workflow_dispatch:

jobs:
  build-config:
    name: CPL stable/stable/latest
    uses: ./.github/workflows/check-pl-compat.yaml
    with:
      catalyst: stable
      pennylane: stable
      lightning: latest
