name: Check CPL latest/latest/stable

on:
  schedule:
    - cron: "20 10 * * 1-5"
  workflow_dispatch:

jobs:
  build-config:
    name: CPL latest/latest/stable
    uses: ./.github/workflows/check-pl-compat.yaml
    with:
      catalyst: latest
      pennylane: latest
      lightning: stable
