name: Check CPL stable/stable/stable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-config:
    name: CPL stable/stable/stable
    uses: ./.github/workflows/check-pl-compat.yaml
    with:
      catalyst: stable
      pennylane: stable
      lightning: stable
