name: Check CPL latest/rc/latest

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-config:
    name: CPL latest/latest/latest
    uses: ./.github/workflows/check-pl-compat.yaml
    with:
      catalyst: latest
      pennylane: release-candidate
      lightning: latest
