name: Check CPL latest/stable/stable

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-config:
    name: CPL latest/stable/stable
    uses: ./.github/workflows/check-pl-compat.yaml
    with:
      catalyst: latest
      pennylane: stable
      lightning: stable
