name: Check CPL stable/latest/stable

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-config:
    name: CPL stable/latest/stable
    uses: ./.github/workflows/check-pl-compat.yaml
    with:
      catalyst: stable
      pennylane: latest
      lightning: stable
